title: International Press book series CDM author support
description: TeX related material for the manuscript preparation for the 
             International Press book series Current Developments in Mathematics 
             (CDM)
show_downloads: true
theme: jekyll-theme-tactile
